production:
  -
    host: 10.0.0.40
    port: 5432
    user: gisuser
    name: timezones
  -
    host: 10.0.0.14
    port: 5432
    user: gisuser
    name: timezones
development:
  -
    host: 127.0.0.1
    port: 5432
    user: gisuser
    name: timezones
